server {
    listen 80;
    server_name ilovezhouzhou.asia;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name ilovezhouzhou.asia;
    
    ssl_certificate /etc/nginx/ssl/ilovezhouzhou.asia.pem;
    ssl_certificate_key /etc/nginx/ssl/ilovezhouzhou.asia.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    
    root /home/root/vue-map-test;
    index index.html;
    
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml;
    gzip_min_length 1000;
    
    location / {
        try_files $uri $uri/ /index.html;
    }
}
